### ISSUE TITLE
{N} 1.7.1

### ISSUE THREAD

**Issue by rborn** [alejonext/NativeLang#2]
Hi, I don't manage to make this work with the  1.7.1 version of {N}.
I changed the module to be bale to get the app context in android

```
var res = utils.ad.getApplicationContext().getResources();
```

 added the `global.L` in app.js but it complains with the next message

```
JS: Cannot find function or filter: L
```

Any idea? Thank you 😄
